config/routes.rb
Rails.application.routes.draw do
  resources :citizens
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'admin/dashboard#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
     user ||= AdminUser.new # guest user (not logged in)
# sectoristas 21,22,23,29
  case user.categoria # a_variable is the variable we want to compare
     when 1,0
          can :manage, :all
     when 2 #quinonez, andres
        can [:read,:update],  [AdminUser]
        can :read, ActiveAdmin::Page, :name =>"Dashboard"
        can [:create,:read,:update,:destroy], [Citizen]
       

      
     else
     
      can :read, ActiveAdmin::Page, :name =>"Dashboard"
   
    end
  
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citizen.rb
class Citizen < ApplicationRecord
    mount_uploader :foto, FotoUploader

validates :dni, presence: true, length: {is: 8 },uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citizens_controller.rb
class CitizensController < InheritedResources::Base
  
  
def jalar(vadni,vpara)
  require 'json'
  require 'open-uri'
   vruta='https://ww1.essalud.gob.pe/sisep/postulante/postulante/postulante_obtenerDatosPostulante.htm?strDni='+vadni
  

  value0 = JSON.parse(open(vruta).read)
  value1 =value0['DatosPerson'][0]
  Citizen.where(id:vpara).update_all( primer_apellido:value1["ApellidoPaterno"],
          segundo_apellido:value1["ApellidoMaterno"],prenombres:value1["Nombres"],
          nacimiento:value1["FechaNacimiento"].to_date,sexo:value1["Sexo"].to_i)
 puts " "       
 puts "COMIENZA"
 puts value1["ApellidoPaterno"].length   
 puts "TERMINA"       
end#def jalar
end#class

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citizens_helper.rb
module CitizensHelper
end

app/views/citizens/_form.html.erb
<%= form_with(model: citizen, local: true) do |form| %>
  <% if citizen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(citizen.errors.count, "error") %> prohibited this citizen from being saved:</h2>

      <ul>
      <% citizen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dni %>
    <%= form.text_field :dni %>
  </div>

  <div class="field">
    <%= form.label :primer_apellido %>
    <%= form.text_field :primer_apellido %>
  </div>

  <div class="field">
    <%= form.label :segundo_apellido %>
    <%= form.text_field :segundo_apellido %>
  </div>

  <div class="field">
    <%= form.label :prenombres %>
    <%= form.text_field :prenombres %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.number_field :sexo %>
  </div>

  <div class="field">
    <%= form.label :estado_civil %>
    <%= form.number_field :estado_civil %>
  </div>

  <div class="field">
    <%= form.label :nacimiento %>
    <%= form.date_select :nacimiento %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto %>
  </div>

  <div class="field">
    <%= form.label :sele1 %>
    <%= form.date_select :sele1 %>
  </div>

  <div class="field">
    <%= form.label :sele2 %>
    <%= form.date_select :sele2 %>
  </div>

  <div class="field">
    <%= form.label :sele3 %>
    <%= form.text_field :sele3 %>
  </div>

  <div class="field">
    <%= form.label :sele4 %>
    <%= form.number_field :sele4 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/citizens/edit.html.erb
<h1>Editing Citizen</h1>

<%= render 'form', citizen: @citizen %>

<%= link_to 'Show', @citizen %> |
<%= link_to 'Back', citizens_path %>

app/views/citizens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Citizens</h1>

<table>
  <thead>
    <tr>
      <th>Dni</th>
      <th>Primer apellido</th>
      <th>Segundo apellido</th>
      <th>Prenombres</th>
      <th>Sexo</th>
      <th>Estado civil</th>
      <th>Nacimiento</th>
      <th>Foto</th>
      <th>Sele1</th>
      <th>Sele2</th>
      <th>Sele3</th>
      <th>Sele4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @citizens.each do |citizen| %>
      <tr>
        <td><%= citizen.dni %></td>
        <td><%= citizen.primer_apellido %></td>
        <td><%= citizen.segundo_apellido %></td>
        <td><%= citizen.prenombres %></td>
        <td><%= citizen.sexo %></td>
        <td><%= citizen.estado_civil %></td>
        <td><%= citizen.nacimiento %></td>
        <td><%= citizen.foto %></td>
        <td><%= citizen.sele1 %></td>
        <td><%= citizen.sele2 %></td>
        <td><%= citizen.sele3 %></td>
        <td><%= citizen.sele4 %></td>
        <td><%= link_to 'Show', citizen %></td>
        <td><%= link_to 'Edit', edit_citizen_path(citizen) %></td>
        <td><%= link_to 'Destroy', citizen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Citizen', new_citizen_path %>

app/views/citizens/new.html.erb
<h1>New Citizen</h1>

<%= render 'form', citizen: @citizen %>

<%= link_to 'Back', citizens_path %>

app/views/citizens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dni:</strong>
  <%= @citizen.dni %>
</p>

<p>
  <strong>Primer apellido:</strong>
  <%= @citizen.primer_apellido %>
</p>

<p>
  <strong>Segundo apellido:</strong>
  <%= @citizen.segundo_apellido %>
</p>

<p>
  <strong>Prenombres:</strong>
  <%= @citizen.prenombres %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @citizen.sexo %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @citizen.estado_civil %>
</p>

<p>
  <strong>Nacimiento:</strong>
  <%= @citizen.nacimiento %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @citizen.foto %>
</p>

<p>
  <strong>Sele1:</strong>
  <%= @citizen.sele1 %>
</p>

<p>
  <strong>Sele2:</strong>
  <%= @citizen.sele2 %>
</p>

<p>
  <strong>Sele3:</strong>
  <%= @citizen.sele3 %>
</p>

<p>
  <strong>Sele4:</strong>
  <%= @citizen.sele4 %>
</p>

<%= link_to 'Edit', edit_citizen_path(@citizen) %> |
<%= link_to 'Back', citizens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elbuen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>